name: CI

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
      - master
      
jobs:
  build:
    runs-on:
      ubuntu-latest
      
    steps:
      - name: checkout
        uses: actions/checkout@v2.5.0
        
      - name: install Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: grant permission to gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: build with gradle
        run: ./gradlew build
        shell: bash
