name: CI

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
      - master
      
env:
  S3_BUCKET_NAME: daydream-freelec-springboot2-build
  PROJECT_NAME: springboot2-webservice
      
jobs:
  build:
    runs-on:
      ubuntu-latest
      
    steps:
      - name: checkout
        uses: actions/checkout@v2.5.0
        
      - name: install Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: grant permission to gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: build with gradle
        run: ./gradlew build
        shell: bash
        
      - name: make zip file
        run: zip -r ./$GITHUB_SHA.zip
        shell: bash
        
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
